### ISSUE TITLE
Columns of files in the ftp server (ftp.biologie.ens.fr/pub/dyogen/PEGASUS/)

### ISSUE THREAD

**Issue by RobTesf** [DyogenIBENS/Regulus#5]
Hello,
So I did not know how to adress this question to you, and I thought here would be easier.
I downloaded the files containing the predictions for enhancers and their targets for the human and zebra fish genomes from your group's NAR paper.
In the paper you calculated a normalized linkage score going from 0 to 1, while in the CNE data file there's no column called linkage score but rather one called segregation.score. Does that represent the linkage score meaning the higher it is the more synteny you observe between the enhancer and the target gene? Related to that do you use any cutoff on the linkage score and/or the phyloP values?
Thanks a lot in advance for your time.

**Comment by dyogen** [comment]
Hi, 
You are correct, the linkage score in the paper is the segregation score in the file, sorry for the confusion. Indeed, the closer to 1.0 the stronger the evolutionary linkage between the CNE and the target gene. We do not specify a threshold. The given linkage score is the highest between the CNE and any surrounding gene within the specified radius. Therefore if the CNE is a regulatory element, then the given gene(s) is (are) the best candidate target(s), even if the score is low. Of course it is understandable that one would want to set a minimal linkage score and/or PhyloP score, but there is no reliable reference to establish these thresholds. 
if you would like to discuss this further I encourage you to email myself (hrc@bio.ens.psl.eu) and my colleague François Giudicelli (francois.giudicelli@bio.ens.psl.eu), who is actively working with the data and has a deeper understanding of the scores and thresholds. 
Best wishes,

Hugues Roest Crollius

**Comment by RobTesf** [comment]
Ok I see. Thanks a lot for your quick reply. I'll send an email if I have more questions.
